### ISSUE TITLE
Implement a message notification feature

### ISSUE THREAD

**Issue by WannianMEI** [TomatoesBurner/Agile-Web-Community-Forum#11]
We need a basic message notification feature:
1. when a poster's post receives a reply, they should go on header and see a notification alert.
2. (TBC) Should we use ajax or websocket?

**Comment by TomatoesBurner** [comment]
OK, it's really an important feature, and I personally recommend using Websocket, it has better immediacy.
If you use ajax: my solution is, js set up a timed task, using ajax every 30 seconds to go to the back-end request to see if there is a message record.

**Comment by eggkiller1101** [comment]
> OK, it's really an important feature, and I personally recommend using Websocket, it has better immediacy. If you use ajax: my solution is, js set up a timed task, using ajax every 30 seconds to go to the back-end request to see if there is a message record.

Since real-time functionality is not so essential for our forum, and AJAX uses standard HTTP requests, which do not require additional learning costs, this also improves our development efficiency.

**Comment by TomatoesBurner** [comment]
I decided to make a message box to record notifications that are created when a post is commented on.

**Comment by TomatoesBurner** [comment]
> I decided to make a message box to record notifications that are created when a post is commented on.

By the way Ajax
