### ISSUE TITLE
Implement the functionality to merge the search dropdown and search box

### ISSUE THREAD

**Issue by eggkiller1101** [TomatoesBurner/Agile-Web-Community-Forum#12]
Currently, our search functionality is split into two separate components: a dropdown menu for selecting the type of search (e.g., search by title, content) and an input box for entering the search query. This separation can lead to a disjointed user experience and increased visual complexity.

**Comment by TomatoesBurner** [comment]
Pay attention to the issue of merging checkboxes and input box overrides, and be careful not to override each other.
