### ISSUE TITLE
Bugfix:wrong form identification

### ISSUE THREAD

**Issue by TomatoesBurner** [TomatoesBurner/Agile-Web-Community-Forum#13]
There is a bug in post-detail.html, here the cursor is moved to the middle, I found that it should be the form is.py form 'Class CommentForm' in the 'content' is currently Stringfeild. should be changed to TextAreaField.

**Comment by eggkiller1101** [comment]
get it!

**Comment by TomatoesBurner** [comment]
![WechatIMG35954](https://github.com/TomatoesBurner/Agile-Web-Community-Forum/assets/48001553/430a394c-213b-43c6-ac45-49e0e7c03e56)
