### ISSUE TITLE
Implement adoption of answers

### ISSUE THREAD

**Issue by TomatoesBurner** [TomatoesBurner/Agile-Web-Community-Forum#15]
Provide a back-end interface to implement the answer to the adoption, but did not implement the adoption of the strategy (need to discuss), such as style changes. The data model will have the following changes.
1. 'CommentModel' . is accpted' ->true
2.'PostsModel' . accepted_answer_id' comment id put inside.

# Ensure that only post authors can accept comments
   if current_user.id ! = post.author_id or post.accepted_answer_id is not None: return redirect(url_for_post).
        return redirect(url_for('postCom.post_detail', post_id=post_id))

**Comment by eggkiller1101** [comment]
I'm feeling confused about how to access status values when interfacing my frontend code with this backend logic.

**Comment by TomatoesBurner** [comment]
> I'm feeling confused about how to access status values when interfacing my frontend code with this backend logic.

Ok, I will help you to finish Jinja2 Html
