### ISSUE TITLE
Add editing functionality for the Profile's personal bio

### ISSUE THREAD

**Issue by WannianMEI** [TomatoesBurner/Agile-Web-Community-Forum#17]
Currently users are unable to edit their personal bio in their profile after initial setup. This issue suggests implementing an edit functionality that allows users to update their bio at any time, thus improving the user's control over their personal information on the platform.

**Comment by eggkiller1101** [comment]
We need to discuss whether to introduce new fields in the database's models.py to store personal information. I suggest adding a bio = TextAreaField(...) field.
