### ISSUE TITLE
 Frontend Representation of an Accepted Answer

### ISSUE THREAD

**Issue by eggkiller1101** [TomatoesBurner/Agile-Web-Community-Forum#18]
I am considering how to visually represent an accepted comment on the frontend. I need to create a distinct effect for the comment component before and after it's accepted. My current idea is: when **hovering over** any comment component, it shows **pink**, indicating that the post author can click it (i.e., to accept it). **After a click**, the accepted comment **remains pink** permanently, while all other **remaining comments turn gray** (and become unclickable). Does anyone have any opinions on this?

**Comment by WannianMEI** [comment]
My idea is that it would be best to show a **popup notification** to the user after successfully accepting an answer. This could also provide an alert in case of any program errors, informing us immediately.

**Comment by TomatoesBurner** [comment]
My advice.
1. It would be a good idea to make all comment components pink when hovering over them (the colour could be something else).
2. when hovering, there could be an 'accept' button, when clicking this button the comment is accepted.
3. When the comment is accepted, there can be a <strong> tag to indicate that the comment is accepted.
