### ISSUE TITLE
Implement: base structure and style

### ISSUE THREAD

**Issue by TheCatFactoryOfV** [TomatoesBurner/Agile-Web-Community-Forum#20]
1. Our front-end project three modules are public, respectively, header, leftside, rightside, the rest according to the task you divided into customized
2. This submission will abstract the html and css of the public modules into base.html and base.css files.

**Comment by TheCatFactoryOfV** [comment]
![微信图片_20230106065921](https://github.com/TomatoesBurner/Agile-Web-Community-Forum/assets/145102537/45a7e22d-317a-4f18-b0e8-ec9eefa16de8)

**Comment by TheCatFactoryOfV** [comment]
![Uploading 1715322307458.png…]()

**Comment by TheCatFactoryOfV** [comment]
![1715322307458](https://github.com/TomatoesBurner/Agile-Web-Community-Forum/assets/145102537/091899ee-1f05-489e-8ce0-02090dcddc67)

**Comment by eggkiller1101** [comment]
Nice try! I am about to modify post-deatil page using this template.
