### ISSUE TITLE
Bugfix: Lack of initiation file

### ISSUE THREAD

**Issue by eggkiller1101** [TomatoesBurner/Agile-Web-Community-Forum#22]
<img width="1178" alt="Screenshot 2024-05-10 at 16 11 42" src="https://github.com/TomatoesBurner/Agile-Web-Community-Forum/assets/79270030/3cc8492e-9a48-4ecc-80e2-e4223749f058">
1 .Error when initialising project (flask run)

**Comment by TomatoesBurner** [comment]
OK I will fix it.I think I forget  git push folder'media/avatars'
