### ISSUE TITLE
Enhancement: posts in homepage displays according to different task types

### ISSUE THREAD

**Issue by eggkiller1101** [TomatoesBurner/Agile-Web-Community-Forum#3]
Currently, all posts are displayed on the homepage without differentiation by task type. To improve user experience and post discoverability, we should enhance the homepage to categorize and display posts according to their respective task types (e.g., Gardening, Housework, etc.).

**Comment by TomatoesBurner** [comment]
Good idea! What do people think of this type of element to prompt the user? Should we put it in the search bar or should we just make a navigation bar and then visit this and click on the jump, since we don't have a lot of types to start with, I'm personally leaning towards a navigation bar?

**Comment by TheCatFactoryOfV** [comment]
I'd prefer to do a left navigation bar.

**Comment by WannianMEI** [comment]
> Good idea! What do people think of this type of element to prompt the user? Should we put it in the search bar or should we just make a navigation bar and then visit this and click on the jump, since we don't have a lot of types to start with, I'm personally leaning towards a navigation bar?

There is no 'type' field in post model

**Comment by TomatoesBurner** [comment]
![WechatIMG111](https://github.com/TomatoesBurner/Agile-Web-Community-Forum/assets/48001553/1261ea11-7612-4ab1-a1eb-71dbfd833c05)

I make a simple demo(static html) ,you guys can see it
