### ISSUE TITLE
Removed the effect of editing the personality signature in the personal home page

### ISSUE THREAD

**Issue by WannianMEI** [TomatoesBurner/Agile-Web-Community-Forum#30]
1. Personalised signatures affect the overall layout and aesthetics.

2. The user interactivity of our project is not very high, the significance of the personalised signature is not very high.

3. Avoid publishing advertisements and phishing links in the personality signature, we don't have an audit system for the time being.

**Comment by TomatoesBurner** [comment]
Ok
