### ISSUE TITLE
Bugfix: Error redirect page

### ISSUE THREAD

**Issue by WannianMEI** [TomatoesBurner/Agile-Web-Community-Forum#34]
Bug：
Delete comment: click the homepage avatar -> click profile -> you can manage the current user's posts and comments.
When clicking delete button in the comment column, it will automatically jump to the posts col

**Comment by TomatoesBurner** [comment]
Do you need me fix @profile_bp.post("/comments/delete/<int:comment_id>") and @profile_bp.post("/posts/delete/<int:post_id>") ? Or do you have any idea?

**Comment by WannianMEI** [comment]
> Do you need me fix @profile_bp.post("/comments/delete/int:comment_id") and @profile_bp.post("/posts/delete/int:post_id") ? Or do you have any idea?

I'll fix it:
1. add a variable tab to mark the switching state of posts and comments.
2. js to read the tab status.

**Comment by TomatoesBurner** [comment]
> > Do you need me fix @profile_bp.post("/comments/delete/int:comment_id") and @profile_bp.post("/posts/delete/int:post_id") ? Or do you have any idea?
> 
> I'll fix it:
> 
> 1. add a variable tab to mark the switching state of posts and comments.
> 2. js to read the tab status.

Ok I will review your code
