### ISSUE TITLE
Enhancement: Implemented the button pagination feature

### ISSUE THREAD

**Issue by eggkiller1101** [TomatoesBurner/Agile-Web-Community-Forum#39]
As a forum website, there will be a large number of posts displayed on the index page, and we need to implement a pagination feature. Currently, there are two options to choose from: traditional pagination buttons or lazy loading. Which method do you think would be better to implement?

**Comment by TomatoesBurner** [comment]
I prefer lazy loading, but I'm trying to do it and it's causing a lot of bugs. Sunday is going to be due, so I'm thinking of combining it with bootrap for the button page flip feature.

**Comment by TheCatFactoryOfV** [comment]
Lazy loading may have better performance in the UI/UX aspect, but technical aspects may be more difficult to achieve.
