### ISSUE TITLE
Page size imbalance

### ISSUE THREAD

**Issue by TomatoesBurner** [TomatoesBurner/Agile-Web-Community-Forum#6]
![WechatIMG3755](https://github.com/TomatoesBurner/Agile-Web-Community-Forum/assets/48001553/42a43351-09e9-4817-94b8-2c2bea534d59)
I think the middle section (the image and the input box) takes up too much of the page, don't you guys think?

**Comment by eggkiller1101** [comment]
Yeah I think so, maybe we need to adjust the css style  to make it more reasonable.

**Comment by WannianMEI** [comment]
I seem to see a wrong word written. Oh, did I read it wrong?

**Comment by TheCatFactoryOfV** [comment]
I think more space is needed up and down the page. Ps: I will modify the material. Sry I m illiterate😂

**Comment by TomatoesBurner** [comment]
Ok. Guys I  will fix it
